name: Testing Github Actions
on:
  push
env:
  PR_NUMBER: github.event.pull_request.number
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: ruby -r "./.github/workflows/test.rb" -e "TestClass.run '${PR_NUMBER}'"