name: Testing Github Actions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_ga:
    name: Test GA
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
      REPO: ${{ github.repository}}
      TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Ruby  
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Install needed gems
        run: |
          gem install pathspec
          gem install faraday

      - name: Fetch List of pull request files
        id: get_rules
        run: ruby -r "./.github/workflows/test.rb" -e "TestClass.new($PR_NUMBER, '$REPO', '$TOKEN').run"
          




