name: Testing Github Actions
on:
  push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/8/files"
          FILES=$(
            curl \
              -H "Accept: application/vnd.github.v3+json" \
              $URL
          )
         ruby -r "./.github/workflows/test.rb" -e "TestClass.run '$FILES'"
