name: Testing Github Actions

on:
  push

jobs:
  test_ga:
    name: Test GA
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REPO: $GITHUB_REPOSITORY
      TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Ruby  
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Fetch List of pull request files
        run: |
          echo $PR_NUMBER
          echo $REPO
          echo $TOKEN
          ruby -r "./.github/workflows/test.rb" -e "TestClass.run '$TOKEN'"
          

          
           

