name: Testing Github Actions

on:
  push

jobs:
  test_ga:
    name: Test GA
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      TOKEN: ${{secrets.GITHUB_TOKEN}}
      CONTEXT: ${{ to_json(github) }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Ruby  
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Fetch List of pull request files
        run: |
          pull_number=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo $pull_number
          echo ${GITHUB_EVENT_PATH}
          echo $PR_NUMBER
          echo ${{ github.event }}
          echo ${GITHUB_REPOSITORY}
          echo $TOKEN
          echo $CONTEXT
          