name: Testing Github Actions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_ga:
    name: Test GA
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
      REPO: ${{ github.repository}}
      TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Ruby  
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Fetch List of pull request files
        run: |
          ruby -r "./.github/workflows/test.rb" -e "TestClass.run '$PR_NUMBER, $REPO, $TOKEN'"
          
          