name: Testing Github Actions
on:
  push
jobs: 
  test:
    runs-on: ubuntu-latest
    env:
      PR_NUM: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: ruby -r "./.github/workflows/test.rb" -e "TestClass.run '${GITHUB_REPOSITORY}'"
      - run: |
          echo $PR_NUM
